version: 2

python:
  version: "3.9"
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
    
sphinx:
  fail_on_warning: true

formats:
  - pdf
  - epub
